### ISSUE TITLE
IMPROVEMENT: Typo "dong"

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/ofn-UserGuide#16]
## Admin Only: Language Checklist for when this Update is Complete
- [x] English
- [ ] French
- [ ] Catalan
- [ ] Italian
- [ ] Russian
- [ ] Turkish
- [ ] Spanish
- [ ] Portuguese

----------------------------------------------------------------------------------------------------------------
## Tell us what you would like to see

**Which language version of the User Guide are you viewing?**
English

**Description**
Group Buy - for bulk ordering 
Typo in 2nd paragraph, 2nd sentence: "By dong so"; Actually there is something wrong in that whole sentence.

**URL of the page/section which you would like improved/updated**
https://guide.openfoodnetwork.org/basic-features/products-1/group-buy-for-bulk-ordering

**In which instance(s) do you know that users are adversely affected by this section of the User Guide in its current form?**
All english speaking

**Suggested New Draft**
By doing so

**Comment by lbwright22** [comment]
English translation updated
