### ISSUE TITLE
Unable to search OFN-User Guide

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/ofn-UserGuide#26]
## Workaround
Only workaround is to page through the guide for what you want.

## Severity
s2 ??

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lauriewayne** [comment]
From Gitbooks support (I have asked them to manually index): 
_Hello Team!

Thanks for reaching out. I'm sorry to hear that you're having issues with your search function. I'm happy to share that we have a possible fix in place.

For the fix to reflect in your account, you can publish another change (anything at all) to cause the app to reindex the space, or if you confirm the affected space, we can manually reindex it for you.

Please let me know if it's working for you now or if you're still having trouble. In addition, if you have any questions, please let me know!

Warm regards,
Marcia_

**Comment by lauriewayne** [comment]
Looks like English is now working - fix (if not working for other books/languages) is to publish something.
